# Generated by Django 3.0.5 on 2020-05-01 05:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0016_auto_20200501_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 1, 5, 4, 17, 245248, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='report',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 1, 5, 4, 17, 245225, tzinfo=utc)),
        ),
    ]
