# Generated by Django 3.0.5 on 2020-04-22 20:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='date_billed',
            field=models.DateField(default=datetime.datetime(2020, 4, 22, 20, 15, 23, 516797, tzinfo=utc)),
        ),
    ]
