# Generated by Django 3.0.5 on 2020-04-22 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20200422_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='user',
            new_name='patient',
        ),
    ]
