# Generated by Django 3.0.5 on 2020-05-01 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_auto_20200426_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_method',
        ),
    ]
