# Generated by Django 3.0.5 on 2020-04-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20200417_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='blood_pressure',
            field=models.CharField(default='0/0', max_length=7),
        ),
        migrations.AddField(
            model_name='record',
            name='height_inches',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11')], default=0),
        ),
        migrations.AddField(
            model_name='record',
            name='prescription',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='pulse',
            field=models.PositiveIntegerField(default=False),
        ),
        migrations.AddField(
            model_name='record',
            name='reason_for_visit',
            field=models.CharField(default='Insert reason for visit here.', max_length=100),
        ),
        migrations.AddField(
            model_name='record',
            name='treatment',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='record',
            name='weight_lbs',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
