# Generated by Django 3.0.5 on 2020-04-28 03:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_auto_20200417_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='appointment_time',
            field=models.TimeField(default=datetime.time(3, 7, 40, 708073)),
        ),
    ]
