# Generated by Django 3.0.5 on 2020-04-28 03:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_auto_20200428_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='appointment_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
