# Generated by Django 3.0.5 on 2020-04-28 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('records', '0008_auto_20200428_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'groups': 1}, on_delete=django.db.models.deletion.CASCADE, related_name='Doc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='record',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'groups': 3}, on_delete=django.db.models.deletion.CASCADE, related_name='Pat', to=settings.AUTH_USER_MODEL),
        ),
    ]
