# Generated by Django 3.0.5 on 2020-04-27 02:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(default=django.utils.timezone.now)),
                ('appointment_time', models.PositiveSmallIntegerField(choices=[(0, '8:00am'), (1, '9:00am'), (2, '10:00am'), (3, '11:00am'), (4, '12:00pm'), (5, '1:00pm'), (6, '2:00pm'), (7, '3:00pm'), (8, '4:00pm')], default=0)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PatientAppointment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
