# Generated by Django 3.0.5 on 2020-04-27 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_auto_20200426_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_time',
            field=models.SmallIntegerField(choices=[(0, '08 AM'), (1, '09 AM'), (2, '10 AM'), (3, '11 AM'), (4, '12 PM'), (5, '01 PM'), (6, '02 PM'), (7, '03 PM'), (8, '04 PM')]),
        ),
    ]
