# Generated by Django 3.0.5 on 2020-04-28 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200428_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patientInsurance',
            field=models.PositiveIntegerField(max_length=12),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patientPhone',
            field=models.IntegerField(max_length=11),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patientSSN',
            field=models.IntegerField(max_length=9),
        ),
    ]
